version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    restart: always
    environment:
      - SILICONFLOW_API_KEY=你的APIKEY
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    restart: always 